### ISSUE TITLE
api/v1/topictree https video urls

### ISSUE THREAD

**Issue by kdadmin** [Khan/khan-api#107]
The latest api/v1/topictree video URLs are now using the HTTPS secure protocol, such as:

  https://cdn.kastatic.org/KA-youtube-converted/l-QFT7XNeb4.mp4/l-QFT7XNeb4.mp4.

The two players I use for my app, VLC and a ffmpeg based one, will only stream over HTTP.
Downloading for offline playback is not a problem.

I'm not sure if these players can be upgraded to accept HTTPS - I will have to investigate.

I'm curious if the HTTPS is causing problems elsewhere?

Thanks,
Gary

**Comment by csilvers** [comment]
Thank you for your report!  You are right that this is a not-necessarily-backwards-compatible change and we should have thought more about it before making the change for /api/v1.

In the meantime, you can just rewrite the urls to use http instead of https; they will work just fine either way.  We changed it to use https to work better with iOS clients, which can be subject to extra security demands.

**Comment by kdadmin** [comment]
Yes, looks like I've fallen behind here.

Both players should update fine for the secure protocol.

Thanks for your quick response.
Gary
