### ISSUE TITLE
KA API Status?

### ISSUE THREAD

**Issue by edbong123** [Khan/khan-api#157]
Hello everyone, I have now reviewed most of the discussion around the Khan API and no one ever really addresses why the old API is being depreciated (apart from common security concerns) and if the is or will be a replacement (using GraphQL)? Could some give a clear answer on what objectives KA is perusing for its developer community? For a non-profit producing a public good not having an API (and worse not having a strategy) is really not acceptable IMHOP. Can some one step up and make a clear statement with a clear rationale?

**Comment by jiridanek** [comment]
> For a non-profit producing a public good not having an API (and worse not having a strategy) is really not acceptable IMHOP.

I disagree with that. It would not be acceptable if KA was a government entity or some state-sponsored enterprise, or state-sanctioned monopoly. Since KA is neither, it is IMO free to do whatever it believes best serves to further its goals and those of its sponsors, using the limited resources it has available.

Having an API is a great enabling facility and it can be very helpful (I used to use that API myself in the past for my project), but we don't have a right to demand such API, or to shame KA into providing it to us.

**Comment by BooLightning** [comment]
I would still love an api.
What would be the best way to get one back on khan?
I would love to help if possible.

**Comment by BooLightning** [comment]
KA uses an api for commenting right?
When you hover over a profile picture in the comments you can see that persons info.
Cant we use that?

**Comment by jeresig** [comment]
Hey folks - sorry, as the README said, we're not planning on continuing to support a public API at this time. We really don't have the bandwidth to work on that while still delivering on our mission. Thanks for your understanding!
