### ISSUE TITLE
Getting `Internal Server Error` on all oauth-signed requests

### ISSUE THREAD

**Issue by jesseditson** [Khan/khan-api#96]
Hey there!

I'm attempting to use the API using an authenticated user.

I've been successfully making calls to the API last week, but as of today, all my requests just return an `Internal Server Error`. I'm using the https://www.npmjs.com/package/khan library to make the request.

I've tried regenerating the tokens for the user to make sure it wasn't a simple expiry or similar issue, to no avail. I'm able to successfully authenticate and regenerate, but signing any request results in an internal server error. When I don't pass an oauth signature, the requests succeed - however, I need to use authenticated endpoints, so will need this issue resolved before I can continue my work.

Let me know if I can provide any more specific details (happy to send over tokens via a private message if necessary).

**Comment by alangpierce** [comment]
Hmm, I can't seem to find any suspicious 500 errors in the logs in the last day. A few questions that might help track this down:

* Do you know what endpoints you were using, specifically? I see errors for /api/v1/playlists/library , but that endpoint is deprecated and has been failing for a long time, I think.
* Is there any message with the 500 error or is it just "Internal Server Error"?
* Just to make sure, the HTTP response code you're getting is 500, right?
* We had a temporary problem earlier today that was causing some server errors, but as far as I can tell it didn't affect any /api/v1 requests. Still, can you confirm that the problem is still happening?

**Comment by jesseditson** [comment]
Wow, so I did some digging, and it looks like I filed a little prematurely - you're absolutely correct, the errors didn't originate on the khan servers, but rather on a different server - I had curried improperly, and was making a request to a server that wasn't yours.

Carry on, sorry about wasting your time!
