### ISSUE TITLE
Question: How do I get authorization to post comments and other normal user actions

### ISSUE THREAD

**Issue by Potato42** [Khan/khan-api#99]
I hope this is the write place to leave a question like this.  Please tell me if it's not.
Anyway, trying to POST to `https://www.khanacademy.org/api/internal/discussions/{comment_key}/replies` and similar things (using the same authorization I have used successfully to GET `https://www.khanacademy.org/api/v1/user`) gives me a 401 code with the following error:

    OAuth error. Invalid signature. Expected signature base string: [insert a OAuth base string here]
The error seems to suggest that if I had a different secret, I would be able to access it as the base string should have been generated correctly, but I don't know how to get that or do anything other than copy my browser cookies to make it work.
If you need it, https://gist.github.com/Potato42/75a04280a157f3c4dd93 (Python 3) is the program I am getting the error on.

**Comment by alangpierce** [comment]
Sorry for the long delay in responding to this. The "invalid signature" error is a common problem to run into in OAuth 1, and it doesn't indicate that you're missing any particular secret. Most likely, the base string when signing (the canonical-form string representing the request that gets signed) is different from what the server is expecting, so you can narrow it down by looking at what base string your OAuth library is using and seeing what's different from what the server sent.

In the past, I've seen incorrect base strings because the request is being modified after it's signed. I've also seen signature problems from edge cases in requests like repeated query parameters. In this case, the POST body may be causing trouble somehow. We definitely have internal clients that make OAuth 1 POST requests through the API, though, so I don't expect that the server has any problems accepting POST requests.

Also note that the endpoint that you're using starts with /api/internal, so it's not officially supported and might change or break in the future. We've also generally only supported GET endpoints in the past; we generally see the API as a way to access data, but not necessarily as a way to interact with the website. But we don't have any technical restrictions stopping the POST request you're trying to make, and you're welcome to try it out as long as you use the endpoint responsibly.
